services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: cc-rag-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./data/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd  
    networks:
      - cc-rag-network
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 10s
      timeout: 5s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    container_name: cc-rag-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - ./data/minio:/minio_data
    command: minio server /minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - cc-rag-network

  milvus:
    image: milvusdb/milvus:v2.4.0
    container_name: cc-rag-milvus
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - ./milvus/milvus.yaml:/milvus/configs/milvus.yaml
      - ./data/milvus:/var/lib/milvus
    ports:
      - "19532:19530"  # 修改为 19532
      - "19093:9091"   # 修改为 19093
    depends_on:
      - etcd
      - minio
    networks:
      - cc-rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 90s

  attu:
    image: zilliz/attu:v2.4.0
    container_name: cc-rag-attu
    environment:
      MILVUS_URL: milvus:19530
    ports:
      - "13002:3000"  # 修改为 13002
    depends_on:
      - milvus
    networks:
      - cc-rag-network

networks:
  cc-rag-network:
    driver: bridge